/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as AdminSpacesRouteImport } from './routes/admin.spaces'
import { Route as AdminSeriesRouteImport } from './routes/admin/series'
import { Route as AdminSpacesIndexRouteImport } from './routes/admin.spaces.index'
import { Route as AdminSpacesNewRouteImport } from './routes/admin.spaces.new'
import { Route as AdminSpacesSlugEditRouteImport } from './routes/admin.spaces.$slug.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpacesRoute = AdminSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeriesRoute = AdminSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpacesIndexRoute = AdminSpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSpacesRoute,
} as any)
const AdminSpacesNewRoute = AdminSpacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminSpacesRoute,
} as any)
const AdminSpacesSlugEditRoute = AdminSpacesSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => AdminSpacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/series': typeof AdminSeriesRoute
  '/admin/spaces': typeof AdminSpacesRouteWithChildren
  '/spaces/$slug': typeof SpacesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/spaces/new': typeof AdminSpacesNewRoute
  '/admin/spaces/': typeof AdminSpacesIndexRoute
  '/admin/spaces/$slug/edit': typeof AdminSpacesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/series': typeof AdminSeriesRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/spaces/new': typeof AdminSpacesNewRoute
  '/admin/spaces': typeof AdminSpacesIndexRoute
  '/admin/spaces/$slug/edit': typeof AdminSpacesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/series': typeof AdminSeriesRoute
  '/admin/spaces': typeof AdminSpacesRouteWithChildren
  '/spaces/$slug': typeof SpacesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/spaces/new': typeof AdminSpacesNewRoute
  '/admin/spaces/': typeof AdminSpacesIndexRoute
  '/admin/spaces/$slug/edit': typeof AdminSpacesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/series'
    | '/admin/spaces'
    | '/spaces/$slug'
    | '/admin/'
    | '/admin/spaces/new'
    | '/admin/spaces/'
    | '/admin/spaces/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/series'
    | '/spaces/$slug'
    | '/admin'
    | '/admin/spaces/new'
    | '/admin/spaces'
    | '/admin/spaces/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/series'
    | '/admin/spaces'
    | '/spaces/$slug'
    | '/admin/'
    | '/admin/spaces/new'
    | '/admin/spaces/'
    | '/admin/spaces/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SpacesSlugRoute: typeof SpacesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spaces': {
      id: '/admin/spaces'
      path: '/spaces'
      fullPath: '/admin/spaces'
      preLoaderRoute: typeof AdminSpacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/series': {
      id: '/admin/series'
      path: '/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AdminSeriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spaces/': {
      id: '/admin/spaces/'
      path: '/'
      fullPath: '/admin/spaces/'
      preLoaderRoute: typeof AdminSpacesIndexRouteImport
      parentRoute: typeof AdminSpacesRoute
    }
    '/admin/spaces/new': {
      id: '/admin/spaces/new'
      path: '/new'
      fullPath: '/admin/spaces/new'
      preLoaderRoute: typeof AdminSpacesNewRouteImport
      parentRoute: typeof AdminSpacesRoute
    }
    '/admin/spaces/$slug/edit': {
      id: '/admin/spaces/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/admin/spaces/$slug/edit'
      preLoaderRoute: typeof AdminSpacesSlugEditRouteImport
      parentRoute: typeof AdminSpacesRoute
    }
  }
}

interface AdminSpacesRouteChildren {
  AdminSpacesNewRoute: typeof AdminSpacesNewRoute
  AdminSpacesIndexRoute: typeof AdminSpacesIndexRoute
  AdminSpacesSlugEditRoute: typeof AdminSpacesSlugEditRoute
}

const AdminSpacesRouteChildren: AdminSpacesRouteChildren = {
  AdminSpacesNewRoute: AdminSpacesNewRoute,
  AdminSpacesIndexRoute: AdminSpacesIndexRoute,
  AdminSpacesSlugEditRoute: AdminSpacesSlugEditRoute,
}

const AdminSpacesRouteWithChildren = AdminSpacesRoute._addFileChildren(
  AdminSpacesRouteChildren,
)

interface AdminRouteChildren {
  AdminSeriesRoute: typeof AdminSeriesRoute
  AdminSpacesRoute: typeof AdminSpacesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSeriesRoute: AdminSeriesRoute,
  AdminSpacesRoute: AdminSpacesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SpacesSlugRoute: SpacesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
